INSERT INTO item_base (name, label) VALUES ('gold_ore', 'Golderz');
INSERT INTO item_base (name, label) VALUES ('gold_coin', 'Goldmünze');
INSERT INTO item_base (name, label) VALUES ('shortsword', 'Kurzschwert');
INSERT INTO item_base (name, label) VALUES ('longsword', 'Langschwert');
INSERT INTO item_base (name, label) VALUES ('shield', 'Schild');
INSERT INTO item_base (name, label) VALUES ('diamond', 'Diamant');
INSERT INTO item_base (name, label) VALUES ('health_potion', 'Lebenstrank');
INSERT INTO item_base (name, label) VALUES ('gold_bar', 'Goldbarren');
INSERT INTO item_base (name, label) VALUES ('bal', 'Artefakt');