name: Build Frontend

on:
  push:
    branches: [ master ]
    paths: ['angular-frontend/**']
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Build Angular App
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: 'npm'
          cache-dependency-path: './angular-frontend/package-lock.json'
      - name: Setup Angular Application
        run: npm ci
        working-directory: ./angular-frontend
      - name: Build Angular Application
        run: ng build
        working-directory: ./angular-frontend
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.CODECAMP23_USERNAME }}
          password: ${{ secrets.CODECAMP23_ACCESS_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          # relative path to the place where source code with Dockerfile is located
          context: ./angular-frontend
          push: true
          tags: lukasbre/realtimecollab-frontend:latest
