name: Build Frontend

on:
  push:
    branches: [ master ]
    paths: ['angular-frontend/**']

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Build Angular App
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: 'npm'
        - run: npm ci
        - run: ng build

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.CODECAMP23_USERNAME }}
          password: ${{ secrets.CODECAMP23_ACCESS_TOKEN }}
          
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          # relative path to the place where source code with Dockerfile is located
          context: ./angular-frontend
          push: true
          tags: lukasbre/realtimecollab-frontend:latest
